import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import './ViewReport.css';
import {
  FileText, X, Zap, Activity, Ruler,
  MessageSquare, Download, ChevronRight, ArrowLeft
} from 'lucide-react';
import PageHeader from '@/components/feed/PageHeader';
import { useProfilePermissions } from '@/hooks/useProfilePermissions';


interface ReportDetail {
  id: string;
  monthYear: string;
  fullDate: string;
  athleteName: string;
  age: number;
  club: string;
  position: string;
  metrics: {
    speed: { rate: string; expected: string };
    agility: { rate: string; expected: string };
    distance: { rate: string; expected: string };
  };
  feedback: string;
}

const ViewReport: React.FC = () => {
  const [view, setView] = useState<'list' | 'detail'>('list');
  const [activeReport, setActiveReport] = useState<ReportDetail | null>(null);
  const navigate = useNavigate();

  // Reports belong to the athlete profile context. Permissions are resolved centrally.
  const { viewerQuery, canViewAthleteReports } = useProfilePermissions("athlete");
  const backTo = `/athlete-profile${viewerQuery}`;

  // Centralized permission gate: any unauthorized viewer is redirected back to the
  // owning athlete profile context (e.g. another athlete viewer).
  useEffect(() => {
    if (!canViewAthleteReports) {
      navigate(backTo, { replace: true });
    }
  }, [canViewAthleteReports, backTo, navigate]);

  // X button: ALWAYS return to the owning athlete profile context, never to /feed.
  const handleCloseList = () => navigate(backTo);

  const reportsData: ReportDetail[] = [
    {
      id: '1',
      monthYear: 'December 2025',
      fullDate: '31/12/2025',
      athleteName: 'Mama',
      age: 24,
      club: 'Forever',
      position: 'Forward',
      metrics: {
        speed: { rate: '12%', expected: '15%' },
        agility: { rate: '8.5', expected: '9.2' },
        distance: { rate: '45 km', expected: '50 km' }
      },
      feedback: "The athlete shows consistent improvement across all key performance indicators. Coaches have noted excellent dedication."
    }
  ];

  const handleOpenDetail = (report: ReportDetail) => {
    setActiveReport(report);
    setView('detail');
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-background to-secondary/5">
      <PageHeader title="Performance Reports" subtitle="AI-generated analysis" backTo={backTo} />

      {view === 'list' && (
        <div className="report-overlay">
          <div className="large-card list-container">
            <div className="card-header">
              <h2>Performance Reports</h2>
              <button type="button" className="icon-btn" aria-label="Close reports" onClick={handleCloseList}><X /></button>
            </div>
            <div className="reports-list">
              {reportsData.map(report => (
                <div key={report.id} className="month-option" onClick={() => handleOpenDetail(report)}>
                  <div className="option-text">
                    <h3>Performance Analysis - {report.monthYear}</h3>
                    <p className="ai-tag">✨ Automatically generated by AI</p>
                  </div>
                  <div className="view-details-link">
                    <span>View Details</span>
                    <ChevronRight size={16} />
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {view === 'detail' && activeReport && (
        <div className="report-overlay">
          <div className="large-card detail-container">
            <div className="card-header">
              <div className="title-section">
                <h1>Monthly Performance Report</h1>
              </div>
              <button type="button" className="icon-btn" aria-label="Close report" onClick={() => setView('list')}><X /></button>
            </div>

            <div className="athlete-brief-grid">
              <div className="grid-item">
                <span className="label">Athlete</span>
                <span className="value">{activeReport.athleteName}, {activeReport.age}</span>
              </div>
              <div className="grid-item">
                <span className="label">Club</span>
                <span className="value">{activeReport.club}</span>
              </div>
              <div className="grid-item">
                <span className="label">Position</span>
                <span className="value">{activeReport.position}</span>
              </div>
              <div className="grid-item">
                <span className="label">Report Date</span>
                <span className="value">{activeReport.fullDate}</span>
              </div>
            </div>

            <table className="metrics-table">
              <thead>
                <tr>
                  <th>Metrics</th>
                  <th>Improvement Rate</th>
                  <th>Expected Performance</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><Zap size={14} className="icon-sub" /> Avg. Speed</td>
                  <td>{activeReport.metrics.speed.rate}</td>
                  <td>{activeReport.metrics.speed.expected}</td>
                </tr>
                <tr>
                  <td><Activity size={14} className="icon-sub" /> Agility Score</td>
                  <td>{activeReport.metrics.agility.rate}</td>
                  <td>{activeReport.metrics.agility.expected}</td>
                </tr>
                <tr>
                  <td><Ruler size={14} className="icon-sub" /> Total Distance</td>
                  <td>{activeReport.metrics.distance.rate}</td>
                  <td>{activeReport.metrics.distance.expected}</td>
                </tr>
              </tbody>
            </table>

            <div className="feedback-card">
              <div className="feedback-header">
                <MessageSquare size={16} /> <span>Coach Feedback</span>
              </div>
              <p className="feedback-text">{activeReport.feedback}</p>
            </div>

            <div className="card-footer">
              <button className="btn-export"><Download size={18} /> Export as PDF</button>
              <button className="btn-close" onClick={() => setView('list')}>Close</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ViewReport;
